apiVersion: v1
kind: Service
metadata:
  name: cart-frontend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: cart-frontend-service-app
  port:
    - port: 5177
      targetPort: 5176
      protocol: TCP
      nodePort: 30009