apiVersion: v1
kind: Service
metadata:
  name: home-frontend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: home-frontend-service-app
  port:
    - port: 5174
      targetPort: 5174
      protocol: TCP
      nodePort: 30007