apiVersion: v1
kind: Service
metadata:
  name: product-frontend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: product-frontend-service-app
  port:
    - port: 5175
      targetPort: 5175
      protocol: TCP
      nodePort: 30008