apiVersion: v1
kind: Service
metadata:
  name: profile-frontend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: profile-frontend-service-app
  port:
    - port: 5178
      targetPort: 5178
      protocol: TCP
      nodePort: 30010