apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-frontend-service
  namespace:  dev

spec:
  minReadySeconds: 3
  replicas: 1

  selector:
    matchLabels:
      app: auth-frontend-service-app
  
  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  template:
    metadata:
      name: auth-frontend-service-pod
      labels:
        app: auth-frontend-service-app
    
    spec:
      containers:
        - name: auth-frontend-service
          image: 984912521466.dkr.ecr.ap-southeast-1.amazonaws.com/shopflow-auth-service-frontend:1.0.0
          envFrom:
            - configMapRef:
                name: auth-frontend-service-config

          imagePullPolicy:  Always

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3

          ports:
            - containerPort: 5173
              protocol: TCP

          resources:
            requests:
              cpu: "50m"
              memory: "80Mi"
            
            limits:
              cpu: "80m"
              memory: "100Mi"