apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: auth-frontend-service-app
  port:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 30006